const Images = {
	logoLight: './img/logo-light.png',
	logoDark: './img/logo-dark.png',
	contactBg: './img/bg-contact.png',
	philippines: './img/philippines.jpg',
	india: './img/india.jpg',
	japan: './img/japan.jpg',
	uae: './img/uae.jpg',
	hongkong: './img/hongkong.jpg',
	singapore: './img/singapore.jpg',
	indo: './img/indonesia.jpg',
	china: './img/china.jpg',
	thailand: './img/thailand.jpg',
	cambodia: './img/cambodia.jpg',
	vietnam: './img/vietnam.jpg',
	malaysia: './img/malaysia.jpg',
	korea: './img/korea.jpg',
	australia: './img/australia.jpg',
	macau: './img/macau.jpg',
	maldives: './img/maldives.jpg',
	newzealand: './img/newzealand.jpg',
	laos: './img/laos.jpg',
	iceland: './img/iceland.jpg',
	myanmmar: './img/myanmar.jpg',
	brunie: './img/brunie.jpg',
	taiwan: './img/taiwan.jpg',
	bgHome: './img/bg-home.jpg',
	bgAbout1: './img/bg-about.jpg',
	bgAbout2: './img/bg-aboutt.jpg',
	bgContact: './img/bg-contact.jpg',
	bgHero: './img/bg-hero.jpg',
	bgHero2: './img/bg-heroo.jpg',
	whatWeDoImg: './img/what-we-do-img.jpg',
	whoWeAreImg: './img/who-we-are-img.jpg',
	bgVision: './img/bg-vision.jpg',
	bgMission: './img/bg-mission.jpg',
	bgTestimonial: './img/bg-testimonial.jpg',
	parallax: './img/parallax.jpg',
	placeholder: './img/placeholder.jpg',
	circle: './img/circle.png',
	bohol1: './img/bohol-1.jpg', // Philippines
	bohol2: './img/bohol-2.jpg',
	bohol3: './img/bohol-3.jpg',
	elnido1: './img/elnido-1.jpg',
	elnido2: './img/elnido-2.jpg',
	elnido3: './img/elnido-3.jpg',
	batangas1: './img/batangas-1.jpg',
	batangas2: './img/batangas-2.jpg',
	batangas3: './img/batangas-3.jpg',
	palawan1: './img/palawan-1.jpg',
	palawan2: './img/palawan-2.jpg',
	palawan3: './img/palawan-3.jpg',
	zambales1: './img/zambales-1.jpg',
	zambales2: './img/zambales-2.jpg',
	zambales3: './img/zambales-3.jpg',
	cebu1: './img/cebu-1.jpg',
	cebu2: './img/cebu-2.jpg',
	cebu3: './img/cebu-3.jpg',
	manila1: './img/manila-1.jpg',
	manila2: './img/manila-2.jpg',
	manila3: './img/manila-3.jpg',
	batanes1: './img/batanes-1.jpg',
	batanes2: './img/batanes-2.jpg',
	batanes3: './img/batanes-3.jpg',
	boracay1: './img/boracay-1.jpg',
	boracay2: './img/boracay-2.jpg',
	boracay3: './img/boracay-3.jpg',
	agra1: './img/agra-1.jpg', // India
	agra2: './img/agra-2.jpg',
	agra3: './img/agra-3.jpg',
	rajasthan1: './img/rajasthan-1.jpg',
	rajasthan2: './img/rajasthan-2.jpg',
	rajasthan3: './img/rajasthan-3.jpg',
	jammu1: './img/jammu-1.jpg',
	jammu2: './img/jammu-2.jpg',
	jammu3: './img/jammu-3.jpg',
	kerala1: './img/kerala-1.jpg',
	kerala2: './img/kerala-2.jpg',
	kerala3: './img/kerala-3.jpg',
	himalayas1: './img/himalayas-1.jpg',
	himalayas2: './img/himalayas-2.jpg',
	himalayas3: './img/himalayas-3.jpg',
	south1: './img/south-1.jpg',
	south2: './img/south-2.jpg',
	south3: './img/south-3.jpg',
	goa1: './img/goa-1.jpg',
	goa2: './img/goa-2.jpg',
	goa3: './img/goa-3.jpg',
	anadaman1: './img/anadaman-1.jpg',
	anadaman2: './img/anadaman-2.jpg',
	anadaman3: './img/anadaman-3.jpg',
	tokyo1: './img/tokyo-1.jpg', // Japan
	tokyo2: './img/tokyo-2.jpg',
	tokyo3: './img/tokyo-3.jpg',
	osaka1: './img/osaka-1.jpg',
	osaka2: './img/osaka-2.jpg',
	osaka3: './img/osaka-3.jpg',
	narita1: './img/narita-1.jpg',
	narita2: './img/narita-2.jpg',
	narita3: './img/narita-3.jpg',
	dubai1: './img/dubai-1.jpg', // UAE
	dubai2: './img/dubai-2.jpg',
	dubai3: './img/dubai-3.JPG',
	abudhabi1: './img/abudhabi-1.jpg',
	abudhabi2: './img/abudhabi-2.jpg',
	abudhabi3: './img/abudhabi-3.jpg',
	singapore1: './img/singapore-1.jpg', // Singapore
	singapore2: './img/singapore-2.jpg',
	singapore3: './img/singapore-3.jpg',
	pattaya1: './img/pattaya-1.jpg', // Thailand
	pattaya2: './img/pattaya-2.jpg',
	pattaya3: './img/pattaya-3.jpg',
	bangkok1: './img/bangkok-1.jpg',
	bangkok2: './img/bangkok-2.jpg',
	bangkok3: './img/bangkok-3.jpg',
	jeju1: './img/jeju-1.jpg', // South Korea
	jeju2: './img/jeju-2.jpg',
	jeju3: './img/jeju-3.jpg',
	seoul1: './img/seoul-1.jpg',
	seoul2: './img/seoul-2.jpg',
	seoul3: './img/seoul-3.jpg',
	sydney1: './img/sydney-1.jpg', // Australia
	sydney2: './img/sydney-2.jpg',
	sydney3: './img/sydney-3.jpg',
	adelaide1: './img/adelaide-1.jpg',
	adelaide2: './img/adelaide-2.jpg',
	adelaide3: './img/adelaide-3.JPG',
	perth1: './img/perth-1.jpg',
	perth2: './img/perth-2.jpg',
	perth3: './img/perth-3.jpg',
	melbourne1: './img/melbourne-1.jpg',
	melbourne2: './img/melbourne-2.jpg',
	melbourne3: './img/melbourne-3.jpg',
	hongkong1: './img/disneyland-3.jpg', // Honkong
	hongkong2: './img/hongkong-1.jpg',
	hongkong3: './img/disneyland-2.jpg',
	cambodia1: './img/cambodia-1.jpg', // Cambodia
	cambodia2: './img/cambodia-2.jpg',
	cambodia3: './img/cambodia-3.jpg',
	vietnam1: './img/vietnam-1.jpg', // Vietnam
	vietnam2: './img/vietnam-2.jpg',
	vietnam3: './img/vietnam-3.jpg',
	malaysia1: './img/malaysia-1.jpg', // Malaysia
	malaysia2: './img/malaysia-2.jpg',
	malaysia3: './img/malaysia-3.jpg',
	indonesia1: './img/indonesia-1.jpg', // Indonesia
	indonesia2: './img/indonesia-2.jpg',
	indonesia3: './img/indonesia-3.jpg',
	china1: './img/china-1.jpg', // China
	china2: './img/china-2.jpg',
	china3: './img/china-3.jpg',
	macau1: './img/macau-1.jpg', // Macau
	macau2: './img/macau-2.jpg',
	macau3: './img/macau-3.jpg',
	maldives1: './img/maldives-1.jpg', // Maldives
	maldives2: './img/maldives-2.jpg',
	maldives3: './img/maldives-3.jpg',
	newzealand1: './img/newzealand-1.jpg', // Newzealand
	newzealand2: './img/newzealand-2.jpg',
	newzealand3: './img/newzealand-3.jpg',
	laos1: './img/laos-1.jpg', // Laos
	laos2: './img/laos-2.jpg',
	laos3: './img/laos-3.jpg',
	iceland1: './img/iceland-1.jpg', // Iceland
	iceland2: './img/iceland-2.jpg',
	iceland3: './img/iceland-3.jpg',
	myanmmar1: './img/myanmmar-1.jpg', // Myanmmar
	myanmmar2: './img/myanmmar-2.jpg',
	myanmmar3: './img/myanmmar-3.jpg',
	brunie1: './img/brunie-1.jpg', // Brunie
	brunie2: './img/brunie-2.jpg',
	brunie3: './img/brunie-3.jpg',
	taiwan1: './img/taiwan-1.jpg', // Taiwan
	taiwan2: './img/taiwan-2.jpg',
	taiwan3: './img/taiwan-3.jpg',
};

export default Images;
